/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hp
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    DefaultTableModel model;
    public EditCourse() {
        initComponents();
        scrl_pane.getVerticalScrollBar().setUnitIncrement(20);
        setRecordsToTable();
    }
    
    public void setRecordsToTable(){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement ps=con.prepareStatement("select * from course");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                String courseId=rs.getString("id");
                String courseName=rs.getString("course_name");
                String coursePrice=rs.getString("course_cost");
                
                Object []obj={courseId,courseName,coursePrice};
                
                model=(DefaultTableModel)tbl_coursedetails.getModel();
                model.addRow(obj);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void clearTable(){
        DefaultTableModel model=(DefaultTableModel)tbl_coursedetails.getModel();
        model.setRowCount(0);
    }
    
    public void addCourse(int id,String courseName,float coursePrice){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement ps=con.prepareStatement("insert into course values(?,?,?)");
            ps.setInt(1, id);
            ps.setString(2, courseName);
            ps.setFloat(3, coursePrice);
            int rowCount=ps.executeUpdate();
            if(rowCount==1){
                JOptionPane.showMessageDialog(this,"Course Added Successfully!");
                clearTable();
                setRecordsToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Course Insertion Failed!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Course Insertion Failed!");
            e.printStackTrace();
        }
    }
    
    public void updateCourse(int id, String coursename, float courseprice){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement ps=con.prepareStatement("update course set course_name=?,course_cost=? where id=?");
            ps.setString(1, coursename);
            ps.setFloat(2, courseprice);
            ps.setInt(3, id);
            int rowCount=ps.executeUpdate();
            if(rowCount==1){
                JOptionPane.showMessageDialog(this,"Course Updated Successfully!");
                clearTable();
                setRecordsToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Course Updation Failed!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Course Updation Failed!");
            e.printStackTrace();
        }
    }
    
    public void deleteCourse(int id){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement ps=con.prepareStatement("delete from course where id=?");
            ps.setInt(1,id);
            int rowCount=ps.executeUpdate();
            if(rowCount==1){
                JOptionPane.showMessageDialog(this,"Course Deleted Successfully!");
                clearTable();
                setRecordsToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Course Deletion Failed!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Course Deletion Failed!");
            e.printStackTrace();
        }
    }
    
    boolean validation(){
        String id=txt_courseid.getText();
        String cname=txt_coursename.getText();
        String cprice=txt_courseprice.getText();
        if(id.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter course id");
            return false;
        }
        if(cname.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter course name");
            return false;
        }
        if(cprice.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter course price");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrl_pane = new javax.swing.JScrollPane();
        panel_main = new javax.swing.JPanel();
        panel_sidebar = new javax.swing.JPanel();
        panel_Logout = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JLabel();
        panel_Home = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        panel_SearchRecord = new javax.swing.JPanel();
        btn_SearchRecord = new javax.swing.JLabel();
        panel_EditCourses = new javax.swing.JPanel();
        btn_newregistration = new javax.swing.JLabel();
        panel_CheckBalance = new javax.swing.JPanel();
        btn_CheckBalance = new javax.swing.JLabel();
        panel_ViewAllRecord = new javax.swing.JPanel();
        btn_ViewAllRecord = new javax.swing.JLabel();
        panel_parent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_coursedetails = new javax.swing.JTable();
        txt_courseid = new javax.swing.JTextField();
        txt_courseprice = new javax.swing.JTextField();
        txt_coursename = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anudip Foundation");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrl_pane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrl_pane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(255, 0, 51));
        panel_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Logout.setBackground(new java.awt.Color(255, 0, 51));
        panel_Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Logout.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/logout.png"))); // NOI18N
        btn_Logout.setText(" Logout");
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
        });
        panel_Logout.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panel_sidebar.add(panel_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 340, 70));

        panel_Home.setBackground(new java.awt.Color(255, 0, 51));
        panel_Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/home.png"))); // NOI18N
        btn_Home.setText(" Home");
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        panel_Home.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        panel_sidebar.add(panel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 70));

        panel_SearchRecord.setBackground(new java.awt.Color(255, 0, 51));
        panel_SearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_SearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_SearchRecord.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_SearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_SearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/search2.png"))); // NOI18N
        btn_SearchRecord.setText("Search Record");
        btn_SearchRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseExited(evt);
            }
        });
        panel_SearchRecord.add(btn_SearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 310, -1));

        panel_sidebar.add(panel_SearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, 70));

        panel_EditCourses.setBackground(new java.awt.Color(255, 0, 51));
        panel_EditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_EditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_newregistration.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_newregistration.setForeground(new java.awt.Color(255, 255, 255));
        btn_newregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/new-user.png"))); // NOI18N
        btn_newregistration.setText("New Registration");
        btn_newregistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newregistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newregistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newregistrationMouseExited(evt);
            }
        });
        panel_EditCourses.add(btn_newregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 70));

        panel_sidebar.add(panel_EditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 340, 70));

        panel_CheckBalance.setBackground(new java.awt.Color(255, 0, 51));
        panel_CheckBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_CheckBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CheckBalance.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_CheckBalance.setForeground(new java.awt.Color(255, 255, 255));
        btn_CheckBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/list.png"))); // NOI18N
        btn_CheckBalance.setText("Check Balance");
        btn_CheckBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CheckBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseExited(evt);
            }
        });
        panel_CheckBalance.add(btn_CheckBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, -1));

        panel_sidebar.add(panel_CheckBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 340, 70));

        panel_ViewAllRecord.setBackground(new java.awt.Color(255, 0, 51));
        panel_ViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_ViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ViewAllRecord.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_ViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_ViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/view all record.png"))); // NOI18N
        btn_ViewAllRecord.setText("View All Record");
        btn_ViewAllRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseExited(evt);
            }
        });
        panel_ViewAllRecord.add(btn_ViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 70));

        panel_sidebar.add(panel_ViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 340, 70));

        panel_main.add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 790));

        panel_parent.setBackground(new java.awt.Color(255, 204, 204));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_coursedetails.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        tbl_coursedetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_Id", "Course_Name", "Course_Price"
            }
        ));
        tbl_coursedetails.getTableHeader().setReorderingAllowed(false);
        tbl_coursedetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_coursedetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_coursedetails);

        panel_parent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 630, 660));

        txt_courseid.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_courseid.setToolTipText("Please enter Course ID");
        panel_parent.add(txt_courseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 300, 40));

        txt_courseprice.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_courseprice.setToolTipText("Please enter Course Price");
        panel_parent.add(txt_courseprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 300, 40));

        txt_coursename.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_coursename.setToolTipText("Please enter Course Name");
        panel_parent.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, 40));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Course Name :");
        panel_parent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, 40));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Course Price :");
        panel_parent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, 40));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Course Id :");
        panel_parent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        btn_update.setBackground(new java.awt.Color(255, 0, 51));
        btn_update.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 204, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setToolTipText("");
        btn_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 255), null, null));
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        panel_parent.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 110, 50));

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 204, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setToolTipText("");
        btn_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 255), null, null));
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        panel_parent.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 110, 50));

        btn_add.setBackground(new java.awt.Color(255, 0, 51));
        btn_add.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 204, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/add2.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.setToolTipText("");
        btn_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 255), null, null));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        panel_parent.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 110, 50));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Edit Course Details");
        panel_parent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 300, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));
        panel_parent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 330, 20));

        panel_main.add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1110, 790));

        scrl_pane.setViewportView(panel_main);

        getContentPane().add(scrl_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1501, 801));

        setSize(new java.awt.Dimension(1515, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        Color c=new Color(255,102,102);
        panel_Logout.setBackground(c);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        Color c=new Color(255,0,51);
        panel_Logout.setBackground(c);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        Home home=new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        Color c=new Color(255,102,102);
        panel_Home.setBackground(c);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        Color c=new Color(255,0,51);
        panel_Home.setBackground(c);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_SearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseClicked
        SearchRecords search=new SearchRecords();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SearchRecordMouseClicked

    private void btn_SearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseEntered
        Color c=new Color(255,102,102);
        panel_SearchRecord.setBackground(c);
    }//GEN-LAST:event_btn_SearchRecordMouseEntered

    private void btn_SearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseExited
        Color c=new Color(255,0,51);
        panel_SearchRecord.setBackground(c);
    }//GEN-LAST:event_btn_SearchRecordMouseExited

    private void btn_newregistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newregistrationMouseEntered
        Color c=new Color(255,102,102);
        panel_EditCourses.setBackground(c);
    }//GEN-LAST:event_btn_newregistrationMouseEntered

    private void btn_newregistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newregistrationMouseExited
        Color c=new Color(255,0,51);
        panel_EditCourses.setBackground(c);
    }//GEN-LAST:event_btn_newregistrationMouseExited

    private void btn_CheckBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseEntered
        Color c=new Color(255,102,102);
        panel_CheckBalance.setBackground(c);
    }//GEN-LAST:event_btn_CheckBalanceMouseEntered

    private void btn_CheckBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseExited
        Color c=new Color(255,0,51);
        panel_CheckBalance.setBackground(c);
    }//GEN-LAST:event_btn_CheckBalanceMouseExited

    private void btn_ViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseEntered
        Color c=new Color(255,102,102);
        panel_ViewAllRecord.setBackground(c);
    }//GEN-LAST:event_btn_ViewAllRecordMouseEntered

    private void btn_ViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseExited
        Color c=new Color(255,0,51);
        panel_ViewAllRecord.setBackground(c);
    }//GEN-LAST:event_btn_ViewAllRecordMouseExited

    private void tbl_coursedetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_coursedetailsMouseClicked
        int rowNum=tbl_coursedetails.getSelectedRow();
        TableModel model=tbl_coursedetails.getModel();
        txt_courseid.setText(model.getValueAt(rowNum, 0).toString());
        txt_coursename.setText((String)model.getValueAt(rowNum, 1));
        txt_courseprice.setText(model.getValueAt(rowNum, 2).toString());
    }//GEN-LAST:event_tbl_coursedetailsMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        int id=Integer.parseInt(txt_courseid.getText());
        String coursename=txt_coursename.getText();
        float courseprice=Float.parseFloat(txt_courseprice.getText());
        if(validation()){
            addCourse(id,coursename,courseprice);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int id=Integer.parseInt(txt_courseid.getText());
        String coursename=txt_coursename.getText();
        float courseprice=Float.parseFloat(txt_courseprice.getText());
        if(validation()){
            updateCourse(id, coursename, courseprice);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int id=Integer.parseInt(txt_courseid.getText());
        if(validation()){
            deleteCourse(id);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_newregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newregistrationMouseClicked
        AddFees add=new AddFees();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_newregistrationMouseClicked

    private void btn_ViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseClicked
        ViewAllRecords records=new ViewAllRecords();
        records.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ViewAllRecordMouseClicked

    private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutMouseClicked

    private void btn_CheckBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseClicked
        // TODO add your handling code here:
        CheckBalance balance=new CheckBalance();
        balance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CheckBalanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_CheckBalance;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Logout;
    private javax.swing.JLabel btn_SearchRecord;
    private javax.swing.JLabel btn_ViewAllRecord;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel btn_newregistration;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_CheckBalance;
    private javax.swing.JPanel panel_EditCourses;
    private javax.swing.JPanel panel_Home;
    private javax.swing.JPanel panel_Logout;
    private javax.swing.JPanel panel_SearchRecord;
    private javax.swing.JPanel panel_ViewAllRecord;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JScrollPane scrl_pane;
    private javax.swing.JTable tbl_coursedetails;
    private javax.swing.JTextField txt_courseid;
    private javax.swing.JTextField txt_coursename;
    private javax.swing.JTextField txt_courseprice;
    // End of variables declaration//GEN-END:variables
}
