/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
//import java.awt.Container;
import java.sql.*;

/**
 *
 * @author hp
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        scrl_pane.getVerticalScrollBar().setUnitIncrement(20);
        getRecords();
        //Container c=getContentPane();
        //c.setBackground(102,153,255);
    }

    public void getRecords(){
        try{
            Connection con=DBConnection.getConnection();
            PreparedStatement ps=con.prepareStatement("select * from fees_details order by receipt_no desc limit 1");
            ResultSet rs=ps.executeQuery();
            rs.next();
            txt_receiptno.setText(rs.getString("receipt_no"));
            txt_paymentmode.setText(rs.getString("payment_mode"));
            String paymentMode=rs.getString("payment_mode");
            if(paymentMode.equalsIgnoreCase("cash")){
                lbl_chequedd.setText("Cheque no:");
                txt_chequedd.setText("-");
                txt_bankname.setText("-");
            }
            if(paymentMode.equalsIgnoreCase("cheque")){
                lbl_chequedd.setText("Cheque no:");
                txt_chequedd.setText(rs.getString("cheque_no"));
                txt_bankname.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("dd")){
                lbl_chequedd.setText("DD no:");
                txt_chequedd.setText(rs.getString("dd_no"));
                txt_bankname.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("card")){
                lbl_chequedd.setText("Cheque no:");
                txt_chequedd.setText("-");
                txt_bankname.setText(rs.getString("bank_name"));
            }
            txt_receivedfrom.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            txt_initialamount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst.setText(rs.getString("sgst"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalinwords.setText(rs.getString("total_in_words"));
            txt_rollno.setText(rs.getString("roll_no"));
            txt_remark.setText(rs.getString("remark"));
            txt_coursename.setText(rs.getString("course_name"));
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrl_pane = new javax.swing.JScrollPane();
        panel_main = new javax.swing.JPanel();
        panel_sidebar = new javax.swing.JPanel();
        panel_Logout = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JLabel();
        panel_Home = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        panel_SearchRecord = new javax.swing.JPanel();
        btn_SearchRecord = new javax.swing.JLabel();
        panel_EditCourses = new javax.swing.JPanel();
        btn_EditCourses = new javax.swing.JLabel();
        panel_CheckBalance = new javax.swing.JPanel();
        btn_CheckBalance = new javax.swing.JLabel();
        panel_ViewAllRecord = new javax.swing.JPanel();
        btn_ViewAllRecord = new javax.swing.JLabel();
        panel_Edit = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        panel_Printing = new javax.swing.JPanel();
        btn_Print = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_receiptno = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        lbl_chequedd = new javax.swing.JLabel();
        txt_chequedd = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_receivedfrom = new javax.swing.JLabel();
        txt_rollno = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_initialamount = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_totalinwords = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anudip Foundation");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrl_pane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrl_pane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panel_main.setBackground(new java.awt.Color(255, 204, 204));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(255, 0, 51));
        panel_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Logout.setBackground(new java.awt.Color(255, 0, 51));
        panel_Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Logout.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/logout.png"))); // NOI18N
        btn_Logout.setText(" Logout");
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
        });
        panel_Logout.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panel_sidebar.add(panel_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 330, 70));

        panel_Home.setBackground(new java.awt.Color(255, 0, 51));
        panel_Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/home.png"))); // NOI18N
        btn_Home.setText(" Home");
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        panel_Home.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        panel_sidebar.add(panel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 70));

        panel_SearchRecord.setBackground(new java.awt.Color(255, 0, 51));
        panel_SearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_SearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_SearchRecord.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_SearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_SearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/search2.png"))); // NOI18N
        btn_SearchRecord.setText("Search Record");
        btn_SearchRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SearchRecordMouseExited(evt);
            }
        });
        panel_SearchRecord.add(btn_SearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 310, -1));

        panel_sidebar.add(panel_SearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 70));

        panel_EditCourses.setBackground(new java.awt.Color(255, 0, 51));
        panel_EditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_EditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_EditCourses.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_EditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btn_EditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/edit2.png"))); // NOI18N
        btn_EditCourses.setText(" Edit Courses");
        btn_EditCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditCoursesMouseExited(evt);
            }
        });
        panel_EditCourses.add(btn_EditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panel_sidebar.add(panel_EditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 330, 70));

        panel_CheckBalance.setBackground(new java.awt.Color(255, 0, 51));
        panel_CheckBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_CheckBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CheckBalance.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_CheckBalance.setForeground(new java.awt.Color(255, 255, 255));
        btn_CheckBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/list.png"))); // NOI18N
        btn_CheckBalance.setText("Check Balance");
        btn_CheckBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CheckBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CheckBalanceMouseExited(evt);
            }
        });
        panel_CheckBalance.add(btn_CheckBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, -1));

        panel_sidebar.add(panel_CheckBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 330, 70));

        panel_ViewAllRecord.setBackground(new java.awt.Color(255, 0, 51));
        panel_ViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_ViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ViewAllRecord.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_ViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_ViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/view all record.png"))); // NOI18N
        btn_ViewAllRecord.setText("View All Record");
        btn_ViewAllRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ViewAllRecordMouseExited(evt);
            }
        });
        panel_ViewAllRecord.add(btn_ViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 70));

        panel_sidebar.add(panel_ViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 330, 70));

        panel_Edit.setBackground(new java.awt.Color(255, 0, 51));
        panel_Edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Edit.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/edit2.png"))); // NOI18N
        btn_Edit.setText(" Edit");
        btn_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        panel_Edit.add(btn_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panel_sidebar.add(panel_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 330, 70));

        panel_Printing.setBackground(new java.awt.Color(255, 0, 51));
        panel_Printing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_Printing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Print.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        btn_Print.setForeground(new java.awt.Color(255, 255, 255));
        btn_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/printer-.png"))); // NOI18N
        btn_Print.setText(" Print");
        btn_Print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PrintMouseExited(evt);
            }
        });
        panel_Printing.add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 70));

        panel_sidebar.add(panel_Printing, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 330, 70));

        panel_main.add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 880));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setForeground(new java.awt.Color(255, 51, 51));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Anudip Foundation");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 50));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 6));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("The following payment in the college office for the year");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 450, 40));

        txt_receiptno.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_receiptno.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 40));

        txt_gstin.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 200, 40));

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Payment mode :");
        panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        txt_paymentmode.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_paymentmode.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 220, 40));

        lbl_chequedd.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lbl_chequedd.setForeground(new java.awt.Color(255, 102, 102));
        lbl_chequedd.setText("Cheque no/dd :");
        panel_print.add(lbl_chequedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 40));

        txt_chequedd.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_chequedd.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_chequedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 40));

        lbl_bankname.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lbl_bankname.setForeground(new java.awt.Color(255, 102, 102));
        lbl_bankname.setText("Bank name :");
        panel_print.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 40));

        txt_bankname.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_bankname.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 250, 40));

        jLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("-");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 20, 40));

        txt_receivedfrom.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_receivedfrom.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 250, 40));

        txt_rollno.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_rollno.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 120, 40));

        txt_year1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 60, 40));

        txt_year2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 60, 40));

        txt_coursename.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_coursename.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 350, 40));

        txt_date.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_date.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 150, 40));

        jLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("GSTIN :");
        panel_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 80, 40));

        jLabel13.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("Date :");
        panel_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 60, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, 290, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 423, 840, 10));

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Receipt no :");
        panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 40));

        jLabel17.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Receipt no :");
        panel_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 40));

        jLabel18.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 102));
        jLabel18.setText("Sr No");
        panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 70, 40));

        jLabel19.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 102));
        jLabel19.setText("Head");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 70, 40));

        jLabel20.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 102));
        jLabel20.setText("Amount");
        panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 80, 40));

        txt_cgst.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_cgst.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 90, 40));

        txt_sgst.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 80, 40));

        jLabel23.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 102));
        jLabel23.setText("SGST 9%");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 90, 40));

        txt_total.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 150, 40));

        txt_initialamount.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_initialamount.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 150, 40));

        jLabel26.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 102));
        jLabel26.setText("CGST 9%");
        panel_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 90, 40));

        jSeparator3.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 840, 10));

        txt_totalinwords.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_totalinwords.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 390, 40));

        txt_remark.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        txt_remark.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 370, 40));

        jLabel28.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 102, 102));
        jLabel28.setText("Receiver Signature");
        panel_print.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 160, 40));

        jSeparator4.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(255, 102, 102));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 290, 10));

        jLabel29.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 102, 102));
        jLabel29.setText("Total in words :");
        panel_print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 140, 40));

        jLabel30.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 102, 102));
        jLabel30.setText("1");
        panel_print.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 50, 40));

        jLabel31.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 102));
        jLabel31.setText("Remark :");
        panel_print.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 100, 40));

        jLabel21.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 102));
        jLabel21.setText("Received from :");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 40));

        jLabel22.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 102));
        jLabel22.setText("Roll no :");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 80, 40));

        panel_main.add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 1000, 740));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 34)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Print Receipt");
        panel_main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 220, 50));

        jSeparator5.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(255, 102, 102));
        panel_main.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 250, 20));

        scrl_pane.setViewportView(panel_main);

        getContentPane().add(scrl_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 890));

        setSize(new java.awt.Dimension(1542, 898));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        Color c=new Color(255,102,102);
        panel_Logout.setBackground(c);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        Color c=new Color(255,0,51);
        panel_Logout.setBackground(c);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        Color c=new Color(255,102,102);
        panel_Home.setBackground(c);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        Color c=new Color(255,0,51);
        panel_Home.setBackground(c);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_SearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseEntered
        Color c=new Color(255,102,102);
        panel_SearchRecord.setBackground(c);
    }//GEN-LAST:event_btn_SearchRecordMouseEntered

    private void btn_SearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseExited
        Color c=new Color(255,0,51);
        panel_SearchRecord.setBackground(c);
    }//GEN-LAST:event_btn_SearchRecordMouseExited

    private void btn_EditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCoursesMouseEntered
        Color c=new Color(255,102,102);
        panel_EditCourses.setBackground(c);
    }//GEN-LAST:event_btn_EditCoursesMouseEntered

    private void btn_EditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCoursesMouseExited
        Color c=new Color(255,0,51);
        panel_EditCourses.setBackground(c);
    }//GEN-LAST:event_btn_EditCoursesMouseExited

    private void btn_CheckBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseEntered
        Color c=new Color(255,102,102);
        panel_CheckBalance.setBackground(c);
    }//GEN-LAST:event_btn_CheckBalanceMouseEntered

    private void btn_CheckBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseExited
        Color c=new Color(255,0,51);
        panel_CheckBalance.setBackground(c);
    }//GEN-LAST:event_btn_CheckBalanceMouseExited

    private void btn_ViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseEntered
        Color c=new Color(255,102,102);
        panel_ViewAllRecord.setBackground(c);
    }//GEN-LAST:event_btn_ViewAllRecordMouseEntered

    private void btn_ViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseExited
        Color c=new Color(255,0,51);
        panel_ViewAllRecord.setBackground(c);
    }//GEN-LAST:event_btn_ViewAllRecordMouseExited

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        Color c=new Color(255,102,102);
        panel_Edit.setBackground(c);
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        Color c=new Color(255,0,51);
        panel_Edit.setBackground(c);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_PrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseEntered
        Color c=new Color(255,102,102);
        panel_Printing.setBackground(c);
    }//GEN-LAST:event_btn_PrintMouseEntered

    private void btn_PrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseExited
        Color c=new Color(255,0,51);
        panel_Printing.setBackground(c);
    }//GEN-LAST:event_btn_PrintMouseExited

    private void btn_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseClicked
        PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf,int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2=(Graphics2D)pg;
                g2.translate(pf.getImageableX(),pf.getImageableY());
                g2.scale(0.47,0.47);
                panel_print.print(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ok=job.printDialog();
        if(ok){
            try{
                job.print();
            }
            catch(PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_PrintMouseClicked

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        UpdateFeesDetails edit=new UpdateFeesDetails();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EditMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        Home home=new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_SearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchRecordMouseClicked
        SearchRecords search=new SearchRecords();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SearchRecordMouseClicked

    private void btn_EditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditCoursesMouseClicked
        EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EditCoursesMouseClicked

    private void btn_ViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewAllRecordMouseClicked
        ViewAllRecords records=new ViewAllRecords();
        records.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ViewAllRecordMouseClicked

    private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutMouseClicked

    private void btn_CheckBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CheckBalanceMouseClicked
        // TODO add your handling code here:
        CheckBalance balance=new CheckBalance();
        balance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CheckBalanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_CheckBalance;
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_EditCourses;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Logout;
    private javax.swing.JLabel btn_Print;
    private javax.swing.JLabel btn_SearchRecord;
    private javax.swing.JLabel btn_ViewAllRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_chequedd;
    private javax.swing.JPanel panel_CheckBalance;
    private javax.swing.JPanel panel_Edit;
    private javax.swing.JPanel panel_EditCourses;
    private javax.swing.JPanel panel_Home;
    private javax.swing.JPanel panel_Logout;
    private javax.swing.JPanel panel_Printing;
    private javax.swing.JPanel panel_SearchRecord;
    private javax.swing.JPanel panel_ViewAllRecord;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JScrollPane scrl_pane;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_chequedd;
    private javax.swing.JLabel txt_coursename;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialamount;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_receivedfrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rollno;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalinwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
