/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Signup_Page extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Page
     */
    String fname,lname,uname,pass,cpass,contact,fullname;
    Date dob;
    int id=0;
    public Signup_Page() {
        initComponents();
    }
    
    public int getId(){
        ResultSet rs=null;
        try{
            Connection con=DBConnection.getConnection();
            String sql="select max(id) from sign_up";
            Statement st=con.createStatement();
            rs=st.executeQuery(sql);
            while(rs.next()){
                id=rs.getInt(1);
                id++;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return id;
    }
    
    boolean validation(){
        fname=txt_fname.getText();
        lname=txt_lname.getText();
        fullname=fname+" "+lname;
        uname=txt_uname.getText();
        pass=psw_pass.getText();
        cpass=psw_cpass.getText();
        dob=date_dob.getDate();
        contact=txt_contact.getText();
        if(fname.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter First Name");
            return false;
        }
        if(lname.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Last Name");
            return false;
        }
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Username");
            return false;
        }
        if(pass.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Password");
            return false;
        }
        if(cpass.equals("")){
            JOptionPane.showMessageDialog(this,"Please Confirm the Password");
            return false;
        }
        if(dob == null){
            JOptionPane.showMessageDialog(this,"Please Enter Date Of Birth");
            return false;
        }
        if(contact.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Contact Number");
            return false;
        }
        if(!pass.equals(cpass)){
            JOptionPane.showMessageDialog(this,"Password not matched");
            return false;
        }
        return true;
    }
    
    public void checkPassword(){
        pass=psw_pass.getText();
        if(pass.length()<8){
            lbl_pass_error.setText("Password should be 8 digit");
        }
        else{
            lbl_pass_error.setText("");
        }
    }
    public void checkContactNo(){
        contact=txt_contact.getText();
        if(contact.length()==10){
            lbl_contact_error.setText("");
        }
        else{
            lbl_contact_error.setText("Contact number should be of 10 digits");
        }
    }
    void insertDetails(){
        SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        String MyDob=format.format(dob);
        try{
            Connection con=DBConnection.getConnection();
            String qry="insert into sign_up values(?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setInt(1, getId());
            ps.setString(2, fullname);
            ps.setString(3, fname);
            ps.setString(4, lname);
            ps.setString(5, uname);
            ps.setString(6, pass);
            ps.setString(7, MyDob);
            ps.setString(8, contact);
            int i=ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this,"Record Inserted");
                Login login=new Login();
                login.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,"Record not inserted");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Record not inserted");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_signup = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_fname = new javax.swing.JLabel();
        lbl_cpass = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        txt_uname = new javax.swing.JTextField();
        psw_pass = new javax.swing.JPasswordField();
        psw_cpass = new javax.swing.JPasswordField();
        lbl_uname = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        lbl_pass = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_pass_error = new javax.swing.JLabel();
        lbl_contact_error = new javax.swing.JLabel();
        date_dob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anudip Foundation");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        lbl_signup.setFont(new java.awt.Font("MS UI Gothic", 0, 40)); // NOI18N
        lbl_signup.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signup.setText("Signup");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(lbl_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_fname.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_fname.setForeground(new java.awt.Color(255, 102, 102));
        lbl_fname.setText("Firstname :");
        jPanel2.add(lbl_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, 168, 28));

        lbl_cpass.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_cpass.setForeground(new java.awt.Color(255, 102, 102));
        lbl_cpass.setText("Confirm Password :");
        jPanel2.add(lbl_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 222, 168, 28));

        lbl_dob.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_dob.setForeground(new java.awt.Color(255, 102, 102));
        lbl_dob.setText("D.O.B :");
        jPanel2.add(lbl_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 269, 168, 28));

        lbl_contact.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(255, 102, 102));
        lbl_contact.setText("Contact no :");
        jPanel2.add(lbl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 318, 168, 28));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_lname.setToolTipText("Please enter lastname");
        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 77, 180, 30));

        txt_uname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_uname.setToolTipText("Please enter username");
        jPanel2.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 125, 180, 30));

        psw_pass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        psw_pass.setToolTipText("Please enter password");
        psw_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psw_passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                psw_passKeyReleased(evt);
            }
        });
        jPanel2.add(psw_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 173, 180, 30));

        psw_cpass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        psw_cpass.setToolTipText("Please confirm password");
        jPanel2.add(psw_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 30));

        lbl_uname.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_uname.setForeground(new java.awt.Color(255, 102, 102));
        lbl_uname.setText("Username :");
        jPanel2.add(lbl_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 126, 168, 28));

        txt_fname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_fname.setToolTipText("Please enter firstname");
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 29, 180, 30));

        lbl_pass.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(255, 102, 102));
        lbl_pass.setText("Password :");
        jPanel2.add(lbl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 174, 168, 28));

        lbl_lname.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        lbl_lname.setForeground(new java.awt.Color(255, 102, 102));
        lbl_lname.setText("Lastname :");
        jPanel2.add(lbl_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 77, 168, 28));

        txt_contact.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_contact.setToolTipText("Please enter contact number");
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contactKeyReleased(evt);
            }
        });
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 317, 180, 30));

        btn_signup.setBackground(new java.awt.Color(255, 0, 51));
        btn_signup.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 204, 255));
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/signup.png"))); // NOI18N
        btn_signup.setText("SignUp");
        btn_signup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 118, 37));

        btn_login.setBackground(new java.awt.Color(255, 0, 51));
        btn_login.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 204, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/Fees_Management_System_images/login.png"))); // NOI18N
        btn_login.setText("LogIn");
        btn_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 118, 37));

        lbl_pass_error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_pass_error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_pass_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 173, 240, 28));

        lbl_contact_error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_contact_error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_contact_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 319, 250, 28));
        jPanel2.add(date_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        if(validation()){
            insertDetails();
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void psw_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psw_passKeyPressed
        checkPassword();
    }//GEN-LAST:event_psw_passKeyPressed

    private void psw_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psw_passKeyReleased
        checkPassword();
    }//GEN-LAST:event_psw_passKeyReleased

    private void txt_contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyPressed
        checkContactNo();
    }//GEN-LAST:event_txt_contactKeyPressed

    private void txt_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyReleased
        checkContactNo();
    }//GEN-LAST:event_txt_contactKeyReleased

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private com.toedter.calendar.JDateChooser date_dob;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_contact_error;
    private javax.swing.JLabel lbl_cpass;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_pass_error;
    private javax.swing.JLabel lbl_signup;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JPasswordField psw_cpass;
    private javax.swing.JPasswordField psw_pass;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
